### ISSUE TITLE
Secure-boot: parsing authority events starting with `[]byte{185 65 36 160}` fails

### ISSUE THREAD

**Issue by twitchy-jsonp** [google/go-attestation#157]
Analysis ongoing, but I have a failing unit test:

```
--- FAIL: TestSecureBootBugThing (0.00s)
    secureboot_test.go:58: failed parsing secureboot state: failed parsing EFI variable authority at event 12: asn1: structure error: tags don't match (16 vs {class:2 tag:25 length:65 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false lax:true name:} certificate @2
    secureboot_test.go:60: <nil>
```

**Comment by twitchy-jsonp** [comment]
This is fixed by https://github.com/mjg59/shim/commit/0b643a2cc0671d875630cbb41180950471f7b082

but we will work around it in the meantime due to widespread use of existing shim. versions

**Comment by mjg59** [comment]
There are two problems here:

1) Shim has an off-by-one error that's resulting in one more byte being logged than is being measured (fixed in https://github.com/rhboot/shim/commit/8a27a4809a6a2b40fb6a4049071bf96d6ad71b50)
2) Shim is measuring the certificate, not the EFI_SIGNATURE_DATA structure (Proposed fix in https://github.com/mjg59/shim/commit/0b643a2cc0671d875630cbb41180950471f7b082)
