### ISSUE TITLE
Implicit platform attestation (question)

### ISSUE THREAD

**Issue by ionut-arm** [google/go-attestation#281]
Hello 👋🏻 

This isn't exactly an issue, more of a question that I didn't know where to raise. Have you considered implicit platform attestation as an option? What I mean is explained (somewhat?) in section 4.12 of the [TCG TAP information model](https://trustedcomputinggroup.org/wp-content/uploads/TNC_TAP_Information_Model_v1.00_r0.36-FINAL.pdf): the AIK is set up with a policy allowing it to be used only when the platform is in a certain state, so its signature when certifying another key (with nonce for freshness) is implicit proof of the platform state.

I couldn't find this implemented here and I was wondering if (a) I didn't look closely enough, (b) there was some reason that made this approach a bad idea, or (c) you didn't see a need for key-and-platform-attestation-in-one.

The reason behind my question is that I was looking for an implementation of this, or was hoping I could draw some inspiration from your approach 😄 

Thanks!

**Comment by ericchiang** [comment]
I don't think there was an explicit reason to not use an AIK with an authPolicy.

For many of our use case, having a key alone is not sufficient to gain access to services. The key represents the device, but we have many measurements that go into the access decision. For example, a device's patch level or security configuration.

State attestation is nice in our existing model, since it's just another measurement we can add to our decision engine. We also still need state attestation in other cases, for example when we're issuing the AIK in the first place.

You'd also need to re-issue the AIK if you ever change your PCRs, such as updating your secureboot settings (not a blocker but something to consider). What your describing sounds a lot like the strategy bitlocker uses for disk encryption keys https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/switch-pcr-banks-on-tpm-2-0-devices#how-does-windows-use-pcrs

**Comment by ionut-arm** [comment]
Thanks for the answer, that makes sense and is a useful perspective.

Our use case is less "one of many checks used in authorization" and more "all we need is proof that this key is stored 'securely', on a 'secure' platform" (<insert some definition of 'secure' here>) - in which case proving both at the same time is preferable. And yeah, the re-issue bit is not ideal, but not really a blocker.

Thanks for the link as well! :)
